### PR TITLE
Added Task.FromResult as return and removed unnecessary async.

### PR DESCRIPTION
**Pull request by jzeferino**

### CODE REVIEW

**Comment by jfversluis** [comment]
Thank you for your efforts! The original author is unfortunately unresponsive and thus it is impossible to create NuGets from this. Please consider adding your code to https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows. Here I can release new NuGet versions. Thanks!

**Comment by jzeferino** [comment]
Ok, i will. @jfversluis this repo is still maintained? Should we talk to the owner to remove it or something? I've seen a lot of existing and maintained forks of it.

**Comment by jfversluis** [comment]
That is what I want to prevent indeed. This repo seems dead.

**Comment by jzeferino** [comment]
@jfversluis I will PR in your repo. 
This repo is under Studyxnet organization. And you are the only guy under that organization. Why don't you remove this repo? or point it to the new repo.

**Comment by jfversluis** [comment]
There other people in the organization that have chosen not to show it on their profile. Since I am not the original author I don’t feel it’s in my place to just shut this down. I’m in a bit of a pickle really. I don’t feel like that’s the right thing to do, but I can’t seem to get in touch with that same author to get stuff done.

**Comment by jzeferino** [comment]
@jbravobr yes you should do that.
Or, since you are in the organization you should have permissions to merge the PRs.
I can help maintain this project if needed.

**Comment by jfversluis** [comment]
I can merge PRs and everything. The thing however I can’t do is manage the nuget packages. So it has no use to keep improving here if we can’t get it to the end-users. Find my repo, add some good stuff and I’ll gladly accept you as a collaborator

**Comment by jzeferino** [comment]
@jfversluis did you talk with the nuget owner and asked for permissions too?

**Comment by jfversluis** [comment]
Of course

**Comment by jzeferino** [comment]
@jfversluis and he didn't reply/want to add you as contributor in nuget?

**Comment by jzeferino** [comment]
@rafaelrmou I want to contribute a continue this project.

Can you please maintain this repo?
If you can't, you can give me permissions for the nuget publishing, and of merging in the organization.

Since this repo ins't maintained there are already a lot of forks of it and this repo will fall in desuse.

**Comment by jfversluis** [comment]
Not to be rude; but does it really matter? I’ve tried this many times, but no response. I don’t start another fork for no reason.

I think if we just switch to my repo and start linking there we will be able to converge from here to there

**Comment by jzeferino** [comment]
@jfversluis I understand your point. I Just need to try it.
I will wait a few more days if @rafaelrmou don't reply I will clearly help in your repo.

**Comment by jzeferino** [comment]
oh and btw @jfversluis why just you started a new fork of the project instead of continue in this repo a create a new publish nuget only?

**Comment by jfversluis** [comment]
It’s been month or even years. So I don’t see how a few days are going to matter. But if that’s what you want, no problem.

And a new fork to not run into any rights issues etc. in the future. This way I’m ensured I always have access to everything. I think I still don’t have full control over this one. So better safe than sorry and again I don’t just want to assume control over someone else’s repo

**Comment by jzeferino** [comment]
I understand your concern and this is Open Source. I just wanted to have a better organization and all the efforts together.But if its not possible, just stick with your fork.

**Comment by jzeferino** [comment]
@rafaelrmou last try.

**Pull request closed without merging**
