### PR TITLE
Fixing issue with  Google Drive, OneDrive on Android

### PR DESCRIPTION
**Pull request by ArtjomP**
Bug with getting content from external content (Google Drive, OneDrive etc) has been fixed. Issues #44 #27 #24

### CODE REVIEW

**Comment by MKuckert** [comment]
Made some small changes to really fix this (see https://github.com/ArtjomP/FilePicker-Plugin-for-Xamarin-and-Windows/pull/1)

**Comment by ShahriatHossain** [comment]
I am getting this exception if I download this branch and replace dll files of my existing setup after building:

System.MissingMethodException: Method 'Plugin.FilePicker.Abstractions.FileData.ReadFully

can anybody help me?

**Comment by ArtjomP** [comment]
Hi there. I was out of my computer. Now I'm back. @ShahriatHossain it seems you forgot to added only Abstract version of the library and forgot to add Android specialization.

**Comment by ShahriatHossain** [comment]
@ArtjomP
Thank you very much for your such a valuable response to me, can you tell me which Abstract version I should add and how to add Android specialization in my xamarin form project?

**Comment by ArtjomP** [comment]
@ShahriatHossain for your Android project you need to add reference to Plugin.FilePicker.dll & Plugin.FilePicker.Abstractions.dll from bin directory of Plugin.FilePicker.Android

**Comment by ArtjomP** [comment]
While this pull request is not merged yet. I've issued nuget package Install-Package pt.Xamarin.Plugin.FilePicker -Version 1.3.6 with changes from this pull request. pt.Xamarin.Plugin.FilePicker

**Comment by golavr** [comment]
The fix works perfect, good job @ArtjomP

**Comment by iupchris10** [comment]
I just installed 1.3.6 and I still receive an error when trying to pick a photo from Google Drive:
**System.IO.DirectoryNotFoundException: Could not find a part of the path "/document/acc=1;doc=46".**

screen shot 2017-09-12 at 10 34 16 am

**Comment by ArtjomP** [comment]
Hi there!
Have you fixed your issue?
Where the problem was?

Sent from Mail for Windows 10

**Comment by iupchris10** [comment]
Hi there!  The issue seemed to go away when I downloaded the source and
compiled the code myself. I still don't have any luck with the Nuget
package. But I've had several issues with the Nuget package anyway,
especially with getting a NotImplementedException in CrossFilePicker.  I
also needed to make specific modifications to the source anyway for my
specific use-case, such as allowing the user to pick ZIP files in iOS from
iCloud drive, displaying the iCloud picker on the active viewmodel instead
of on UiWIndow, and adding external storage permission checks in for
Android for OS >= 6.0.

If I run into any more issues, I'll let you know. I might make a branch in
the future to address some of the above concerns.

-Chris

**Comment by jfversluis** [comment]
Can we get this code into the fork here: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows?

Since this seems abandoned (again) I've created another fork and will start pushing NuGets from there

**Pull request closed without merging**
