### PR TITLE
Fix null filename from icloud drive

### PR DESCRIPTION
**Pull request by Orillion360**
I had a problem where iCloud drive would return null for doc.LocalizedName. This fix now takes the filename from the FileURL in case doc.LocalizedName is empty.

### CODE REVIEW

**Comment by jfversluis** [comment]
@Orillion360 I've created a fork with own NuGet since this repo seems abandoned, would you be interested in recreating this PR in mine? https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows

**Comment by rafaelrmou** [comment]
It's not abandoned... Only short time to see here :(

**Comment by jfversluis** [comment]
Great! Hi! Because it had not been updated for months and no replies on anything I thought it was, I am very sorry @rafaelrmou. If you want to I can help you out?

**Comment by rafaelrmou** [comment]
I add u to TEAM :)

If u can do de merges we will update de original nuget https://www.nuget.org/packages/Xam.Plugin.FilePicker/

**Comment by rafaelrmou** [comment]
Thank u :)

**Comment by jfversluis** [comment]
I will remove mine and merge the changes in this one, great!

**Comment by rafaelrmou** [comment]
Awesome, Thank u :D

**Pull request merged**
